/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as BulletinsMoisRouteImport } from './routes/bulletins-mois'
import { Route as CourrierRouteImport } from './routes/courrier'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as EnvoisRouteImport } from './routes/envois'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ListeSalairesRouteImport } from './routes/liste-salaires'
import { Route as MensuelRouteImport } from './routes/mensuel'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PrimesRouteImport } from './routes/primes'
import { Route as BulletinIdRouteImport } from './routes/bulletin.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinsMoisRoute = BulletinsMoisRouteImport.update({
  id: '/bulletins-mois',
  path: '/bulletins-mois',
  getParentRoute: () => rootRouteImport,
} as any)
const CourrierRoute = CourrierRouteImport.update({
  id: '/courrier',
  path: '/courrier',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvoisRoute = EnvoisRouteImport.update({
  id: '/envois',
  path: '/envois',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeSalairesRoute = ListeSalairesRouteImport.update({
  id: '/liste-salaires',
  path: '/liste-salaires',
  getParentRoute: () => rootRouteImport,
} as any)
const MensuelRoute = MensuelRouteImport.update({
  id: '/mensuel',
  path: '/mensuel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimesRoute = PrimesRouteImport.update({
  id: '/primes',
  path: '/primes',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinIdRoute = BulletinIdRouteImport.update({
  id: '/bulletin/$id',
  path: '/bulletin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/bulletins-mois': typeof BulletinsMoisRoute
  '/courrier': typeof CourrierRoute
  '/employes': typeof EmployesRoute
  '/envois': typeof EnvoisRoute
  '/historique': typeof HistoriqueRoute
  '/liste-salaires': typeof ListeSalairesRoute
  '/mensuel': typeof MensuelRoute
  '/planning': typeof PlanningRoute
  '/primes': typeof PrimesRoute
  '/bulletin/$id': typeof BulletinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/bulletins-mois': typeof BulletinsMoisRoute
  '/courrier': typeof CourrierRoute
  '/employes': typeof EmployesRoute
  '/envois': typeof EnvoisRoute
  '/historique': typeof HistoriqueRoute
  '/liste-salaires': typeof ListeSalairesRoute
  '/mensuel': typeof MensuelRoute
  '/planning': typeof PlanningRoute
  '/primes': typeof PrimesRoute
  '/bulletin/$id': typeof BulletinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/bulletins-mois': typeof BulletinsMoisRoute
  '/courrier': typeof CourrierRoute
  '/employes': typeof EmployesRoute
  '/envois': typeof EnvoisRoute
  '/historique': typeof HistoriqueRoute
  '/liste-salaires': typeof ListeSalairesRoute
  '/mensuel': typeof MensuelRoute
  '/planning': typeof PlanningRoute
  '/primes': typeof PrimesRoute
  '/bulletin/$id': typeof BulletinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/bulletins-mois'
    | '/courrier'
    | '/employes'
    | '/envois'
    | '/historique'
    | '/liste-salaires'
    | '/mensuel'
    | '/planning'
    | '/primes'
    | '/bulletin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/bulletins-mois'
    | '/courrier'
    | '/employes'
    | '/envois'
    | '/historique'
    | '/liste-salaires'
    | '/mensuel'
    | '/planning'
    | '/primes'
    | '/bulletin/$id'
  id:
    | '__root__'
    | '/'
    | '/archives'
    | '/bulletins-mois'
    | '/courrier'
    | '/employes'
    | '/envois'
    | '/historique'
    | '/liste-salaires'
    | '/mensuel'
    | '/planning'
    | '/primes'
    | '/bulletin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesRoute: typeof ArchivesRoute
  BulletinsMoisRoute: typeof BulletinsMoisRoute
  CourrierRoute: typeof CourrierRoute
  EmployesRoute: typeof EmployesRoute
  EnvoisRoute: typeof EnvoisRoute
  HistoriqueRoute: typeof HistoriqueRoute
  ListeSalairesRoute: typeof ListeSalairesRoute
  MensuelRoute: typeof MensuelRoute
  PlanningRoute: typeof PlanningRoute
  PrimesRoute: typeof PrimesRoute
  BulletinIdRoute: typeof BulletinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletins-mois': {
      id: '/bulletins-mois'
      path: '/bulletins-mois'
      fullPath: '/bulletins-mois'
      preLoaderRoute: typeof BulletinsMoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courrier': {
      id: '/courrier'
      path: '/courrier'
      fullPath: '/courrier'
      preLoaderRoute: typeof CourrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envois': {
      id: '/envois'
      path: '/envois'
      fullPath: '/envois'
      preLoaderRoute: typeof EnvoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste-salaires': {
      id: '/liste-salaires'
      path: '/liste-salaires'
      fullPath: '/liste-salaires'
      preLoaderRoute: typeof ListeSalairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensuel': {
      id: '/mensuel'
      path: '/mensuel'
      fullPath: '/mensuel'
      preLoaderRoute: typeof MensuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primes': {
      id: '/primes'
      path: '/primes'
      fullPath: '/primes'
      preLoaderRoute: typeof PrimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin/$id': {
      id: '/bulletin/$id'
      path: '/bulletin/$id'
      fullPath: '/bulletin/$id'
      preLoaderRoute: typeof BulletinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesRoute: ArchivesRoute,
  BulletinsMoisRoute: BulletinsMoisRoute,
  CourrierRoute: CourrierRoute,
  EmployesRoute: EmployesRoute,
  EnvoisRoute: EnvoisRoute,
  HistoriqueRoute: HistoriqueRoute,
  ListeSalairesRoute: ListeSalairesRoute,
  MensuelRoute: MensuelRoute,
  PlanningRoute: PlanningRoute,
  PrimesRoute: PrimesRoute,
  BulletinIdRoute: BulletinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
