/** Effectif réel – Polyclinique de Poitiers (liste des salaires, juillet/août 2026). */
import { nouvelEmploye, type Employe } from "./payroll";

export const EMPLOYES_POITIERS: Employe[] = [
  {
    ...nouvelEmploye("ABAMI ROSINE BELIE", 106950),
    matricule: "POI-001",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("ACHALE RODERICK ESSOH", 195941),
    matricule: "POI-002",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("AMEFFO LUCIE C.", 122621),
    matricule: "POI-003",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("ATCHEMO GENEVIEVE", 123964),
    matricule: "POI-004",
    societe: "SGC",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("BIAHEU AMANDINE", 117055),
    matricule: "POI-005",
    societe: "SGC",
    primesFixes: 6000,
  },
  {
    ...nouvelEmploye("BILOA ELOUNDOU GERTRUDE", 130665),
    matricule: "POI-006",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("BINAMA PATRICK JUNIOR", 102450),
    matricule: "POI-007",
    societe: "SOFINA",
  },
  {
    ...nouvelEmploye("BONGKO CONFIDENCE BERI", 126744),
    matricule: "POI-008",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("CHEUMEN LARISSA", 119555),
    matricule: "POI-009",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("CHOUKE KETECHEMEN CHANCELLE", 143659),
    matricule: "POI-010",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("DEFFO MATSING OLIVE P.", 152972),
    matricule: "POI-011",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("DEUMAGA J. GABRIEL", 110753),
    matricule: "POI-012",
    societe: "SGC",
    primesFixes: 24500,
  },
  {
    ...nouvelEmploye("DIN JOSEPH", 97259),
    matricule: "POI-013",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("DJEUKUI MBIDJOU CHRISTIAN PAULIN", 117055),
    matricule: "POI-014",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("DJUEYA RUPHILE", 29165),
    matricule: "POI-015",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("DONGMO LAURA BRENDA", 117055),
    matricule: "POI-016",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("DONMEZA NGUEMFO F", 125967),
    matricule: "POI-017",
    societe: "SGC",
    primesFixes: 2500,
  },
  {
    ...nouvelEmploye("EBA MBALA LUC PAULIN", 144186),
    matricule: "POI-018",
    societe: "SGC",
    primesFixes: 49500,
  },
  {
    ...nouvelEmploye("ETOUNOU ROSALIE", 116681),
    matricule: "POI-019",
    societe: "SGC",
    primesFixes: 3500,
  },
  {
    ...nouvelEmploye("FEUSSI NZUMO BABEL AMEDEE", 146903),
    matricule: "POI-020",
    societe: "SGC",
    primesFixes: 22500,
  },
  {
    ...nouvelEmploye("FOCHIVE ABOUBAKAR", 90660),
    matricule: "POI-021",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("FOGANG HELENE", 162659),
    matricule: "POI-022",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("FOUDA ZOA RUPHINE ANNETTE", 103664),
    matricule: "POI-023",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("GAINYO N.G.C.", 101526),
    matricule: "POI-024",
    societe: "SGC",
    primesFixes: 37500,
  },
  {
    ...nouvelEmploye("GAMGO FANAISE LEOPOLDINE", 131334),
    matricule: "POI-025",
    societe: "SGC",
    primesFixes: 2500,
  },
  {
    ...nouvelEmploye("GHAMBU NGANJINE EPSE MOUNTAPMBEME AWAW", 121055),
    matricule: "POI-026",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("GNOCHE KAMGA ARLETTE", 180868),
    matricule: "POI-027",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("GUEPA BOUKAM MARLYSE", 125320),
    matricule: "POI-028",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("HOKACHI LAURE FLORE", 97450),
    matricule: "POI-029",
    societe: "SOFINA",
  },
  {
    ...nouvelEmploye("ITABA FELIX DIGSON", 69920),
    matricule: "POI-030",
    societe: "SGC",
    primesFixes: 5000,
  },
  {
    ...nouvelEmploye("KENGNE DEMANOU WILLIANE", 66766),
    matricule: "POI-031",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("LEUNDEU TCHOKEUANDEU CARMEL WILFRIED", 122055),
    matricule: "POI-032",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("LONJEH ELISABETH", 103172),
    matricule: "POI-033",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("LOUONJOU SYLVIE", 142692),
    matricule: "POI-034",
    societe: "SGC",
    primesFixes: 2500,
  },
  {
    ...nouvelEmploye("MAGUE KAMDEM BERTILLE VICTOIRE", 133303),
    matricule: "POI-035",
    societe: "SGC",
    primesFixes: 1000,
  },
  {
    ...nouvelEmploye("MAKOUET RABIATOU", 80783),
    matricule: "POI-036",
    societe: "SOFINA",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("MATSINDJOU OUMBE CHRISTELLE", 121055),
    matricule: "POI-037",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("MBAHO NJONJOUO KELIANE", 126950),
    matricule: "POI-038",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("MBOUANGOUORE EVELINE", 127039),
    matricule: "POI-039",
    societe: "SGC",
    primesFixes: 10000,
  },
  {
    ...nouvelEmploye("MBU ROSE", 120437),
    matricule: "POI-040",
    societe: "SGC",
    primesFixes: 1000,
  },
  {
    ...nouvelEmploye("MENA ATSING LAURENTINE NICAISE", 122694),
    matricule: "POI-041",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("MENO EMMANUEL", 129165),
    matricule: "POI-042",
    societe: "SGC",
    primesFixes: 7500,
  },
  {
    ...nouvelEmploye("MEPE AMANDINE GISELE", 133592),
    matricule: "POI-043",
    societe: "SGC",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("MIANFO DONGMO CHIMENE MEDINE", 128556),
    matricule: "POI-044",
    societe: "SGC",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("MIDENNA PASCAL", 138434),
    matricule: "POI-045",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("MIMCHE CAROLE MIKANO", 142829),
    matricule: "POI-046",
    societe: "SGC",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("MOSSI HORTENSE PASCALINE", 140969),
    matricule: "POI-047",
    societe: "SGC",
    primesFixes: 7500,
  },
  {
    ...nouvelEmploye("MOTOUM EP. FONGUEN FLORE", 80160),
    matricule: "POI-048",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("MOUMIE MOHAMED SHERIF DAIROU", 119555),
    matricule: "POI-049",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("MOUNCHILI YAYA LEDUR", 102017),
    matricule: "POI-050",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("MOUTOME NYA FRANCOISE", 143787),
    matricule: "POI-051",
    societe: "SGC",
    primesFixes: 24500,
  },
  {
    ...nouvelEmploye("NDONGO EBONGUE MONIQUE", 114979),
    matricule: "POI-052",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("NGAHA EP. KWATCHET M.", 160766),
    matricule: "POI-053",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("NGO NYETAM GERTRUDE ODETTE ING", 107450),
    matricule: "POI-054",
    societe: "SGC",
    primesFixes: 27500,
  },
  {
    ...nouvelEmploye("NGOUA EPALLE CEDRIC BRICE", 121055),
    matricule: "POI-055",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("NJIKAM EMMANUEL", 124698),
    matricule: "POI-056",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("NJIMAH JOUH BINTOU", 212806),
    matricule: "POI-057",
    societe: "SGC",
    primesFixes: 9500,
  },
  {
    ...nouvelEmploye("NJUNDAM MAMA", 192987),
    matricule: "POI-058",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("NKANA CHRISTINE GEORGETTE", 119405),
    matricule: "POI-059",
    societe: "SGC",
    primesFixes: 14500,
  },
  {
    ...nouvelEmploye("NOUBISSI DJIOKOU JEAN MARIE", 128556),
    matricule: "POI-060",
    societe: "SGC",
    primesFixes: 84500,
  },
  {
    ...nouvelEmploye("NSONGAN FREDERIC", 91750),
    matricule: "POI-061",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("NYAKE NADINE", 306200),
    matricule: "POI-062",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("NYONGMA NSENE NADINE", 152158),
    matricule: "POI-063",
    societe: "SGC",
    primesFixes: 24500,
  },
  {
    ...nouvelEmploye("ONDOUA MBENGONO BRICE ALVANY", 106278),
    matricule: "POI-064",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("POUGOUE EP. LENYA CHRISTINE", 253052),
    matricule: "POI-065",
    societe: "SGC",
    primesFixes: 49500,
  },
  {
    ...nouvelEmploye("SAMEKI SERGES", 162147),
    matricule: "POI-066",
    societe: "SGC",
    primesFixes: 19500,
  },
  {
    ...nouvelEmploye("SIBEH AISSATOU", 87450),
    matricule: "POI-067",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("SIGNE YAMDJEU VANESSA", 150896),
    matricule: "POI-068",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("SILIKI BONNY", 122768),
    matricule: "POI-069",
    societe: "SGC",
    primesFixes: 13500,
  },
  {
    ...nouvelEmploye("SIMO BOUPDA FRANCK BEAUREEL", 171806),
    matricule: "POI-070",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("SIPOUO POUTONG ELISE CHESLIE", 222065),
    matricule: "POI-071",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TAMO CHATCHUENG JOSIANE", 110387),
    matricule: "POI-072",
    societe: "SGC",
    primesFixes: 41300,
  },
  {
    ...nouvelEmploye("TAWAH EMMANUEL BAHBOT", 103000),
    matricule: "POI-073",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TCHAGA LEUMALIEU MELAINE VASTAN", 128539),
    matricule: "POI-074",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TCHEUKO BYLLI LEY", 68303),
    matricule: "POI-075",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TCHIEGUE JEAN GEORGES", 371918),
    matricule: "POI-076",
    societe: "SGC",
    primesFixes: 109500,
  },
  {
    ...nouvelEmploye("TCHOKOTE AUDREY CASANDRE", 148302),
    matricule: "POI-077",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("TCHOUANKEM SALLY MEUTOU MOJOKO", 121055),
    matricule: "POI-078",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TCHOUNTA LINKIO NELY", 155851),
    matricule: "POI-079",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("TCHUITCHAM SUZANNE", 74866),
    matricule: "POI-080",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TESSA KAMILA JOYCE", 103000),
    matricule: "POI-081",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TEUMEN EMATOU ANNCIK PATIENCE", 110563),
    matricule: "POI-082",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("TIANGUEU KAMENI VANEL FLORA", 171806),
    matricule: "POI-083",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("TIOPA MODI ANNIE FLORE", 89841),
    matricule: "POI-084",
    societe: "SGC",
    primesFixes: 4500,
  },
  {
    ...nouvelEmploye("TSOBZE ZEBAZE BRICE H.", 152821),
    matricule: "POI-085",
    societe: "SGC",
    primesFixes: 127000,
  },
  {
    ...nouvelEmploye("WAGOUM BOGNOU EPSE TCHOFFO FLORENCE", 133167),
    matricule: "POI-086",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("WAHEU MONTHE ARNAUD", 126506),
    matricule: "POI-087",
    societe: "SGC",
  },
  {
    ...nouvelEmploye("DONGMO JEAN PAUL (GROUPE)", 199500),
    matricule: "POI-088",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("DJONGOUE KAMENI BERTRAND", 149500),
    matricule: "POI-089",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("NGATCHO DANLE ROMEO", 149500),
    matricule: "POI-090",
    societe: "SESAME",
  },
  {
    ...nouvelEmploye("TAKOUGANG (JARDINIER)", 15000),
    matricule: "POI-091",
    societe: "SOFINA",
  },
  {
    ...nouvelEmploye("TCHAKOUNTE FRANCK MICHAEL", 350000),
    matricule: "POI-092",
    societe: "SOFINA",
  },
];
