import { chromium } from "playwright";
const [url, out] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(url, { waitUntil: "networkidle" });
await page.waitForTimeout(Number(process.env.WAIT || 8000));
await page.emulateMedia({ media: "print" });
await page.pdf({ path: out, format: "A4", printBackground: true });
await browser.close();
console.log("pdf ok");
