import { chromium } from "playwright";
const [url, out] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 794, height: 1123 } });
await page.goto(url, { waitUntil: "networkidle" });
await page.waitForTimeout(Number(process.env.WAIT || 8000));
await page.emulateMedia({ media: "print" });
await page.screenshot({ path: out, fullPage: true });
await browser.close();
console.log("png ok");
